title: GMRicker
plugins:
- jekyll-remote-theme
remote_theme: "abhinavs/moonwalk"
theme_config:
  appearance: "dark"
  appearance_toggle: true 
  show_navbar: true
  show_projects: true
  back_home_text: "home"
